steps:
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - -c
      - |
        echo "DATABASE_URL: $DATABASE_URL"
    secretEnv: ['DATABASE_URL']

availableSecrets:
  secretManager:
    - versionName: projects/709767355109/secrets/orders_database_url/versions/1
      env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY
